title: Bonsai @ HHMI Janelia 2024
description: Bonsai introduction at HHMI Janelia 2024.
google_analytics:
theme: minima
baseurl: "/janelia-2024"

twitter_username: bonsai_rx
github_username:  neurogears

kramdown:
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"
